name: My first workflow

on: push

jobs:
  my_first_workflow_job:
    run-on: ubuntu-latest
    steps:
      - name: Echo task description
        run: echo "My firt workflow job"

      - name: List files
        run: ls -la
      
      - name: Read the file README.md
        run: cat README.md